[global]
backend              = "portaudio"      # most trouble-free on macOS
volume_controller    = "softvol"        # lets spotifyd manage volume
bitrate              = 320              # 96/160/320 kb/s
cache_path           = "/Users/you/Library/Caches/spotifyd"
volume_normalisation = false
max_cache_size       = 524288000
device_type          = "speaker"

