#!/bin/bash
# Auto-generated by gbrain autopilot --install; hardened for Jacob's local agent stack.
# Load only the Hermes secret env instead of broad interactive shell profiles.
export PATH="$HOME/.bun/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
set -a
source "$HOME/.hermes/.env" 2>/dev/null || true
set +a
exec '/Users/jmogainz/.bun/bin/gbrain' autopilot --repo '/Users/jmogainz/brain'
