#!/bin/bash

# Log file for debugging
LOGFILE="/var/log/monitor_hotplug.log"

# Function to check if any external monitor is connected
external_monitor_connected() {
    xrandr | grep -q -E " connected [^(eDP|LVDS)]"
}

echo "$(date): Monitor hotplug event detected." >> "$LOGFILE"

if external_monitor_connected; then
    echo "$(date): External monitor detected. Configuring displays..." >> "$LOGFILE"
    # Apply the monitor configuration generated by Arandr
    xrandr --output eDP-1 --off --output DP-1 --off --output HDMI-1 --off --output DP-2 --off --output DP-3 --off --output DP-4 --mode 3840x2160 --pos 6480x0 --rotate right --output DP-5 --off --output DP-1-0 --off --output DP-1-1 --off --output HDMI-1-0 --primary --mode 3840x2160 --pos 0x0 --rotate left --output DP-1-2 --off --output DP-1-0.6.6 --mode 3840x2160 --pos 2160x0 --rotate right --output DP-1-0.5.5 --mode 3840x2160 --pos 4320x0 --rotate left
else
    echo "$(date): No external monitor detected. Skipping configuration." >> "$LOGFILE"
fi
