# ~/.config/alacritty/alacritty.toml

import = ["~/.config/alacritty/dracula.toml"]

[font]
normal = { family = "JetBrainsMono Nerd Font" }
size = 15.5

[env]
TERM = "xterm-256color"

[window]

[scrolling]
history = 20000
