set number
set relativenumber

let g:netrw_bufsettings = 'noma nomod nu rnu nobl nowrap ro'

set shada^=%,'1000

set undofile
set undodir=~/.local/state/nvim/undo//

if !isdirectory(expand(&undodir))
  call mkdir(expand(&undodir), "p")
endif

set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set smartindent

set sessionoptions+=buffers
autocmd VimLeavePre * silent! mksession! ~/.config/nvim/Session.vim
autocmd VimEnter * silent! source ~/.config/nvim/Session.vim

set cursorline
